[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add this section for Hedera Testnet
[rpc_endpoints]
testnet = "${RPC_URL}"

# Add this section for verification
[profile.default.verifiers]
sourcify_testnet = { url = "https://server-verify.hashscan.io/" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
